### ISSUE TITLE
Omni completion doesn't work

### ISSUE THREAD

**Issue by Arafat245** [ehzShelter/vimMethod#1]
CTRL-n doesn't work

**Comment by ehzShelter** [comment]
Omni completion <C-n> is replaced with tab....using superTab plugin...see that

**Comment by ehzShelter** [comment]
:map run this command in vim
or
:map <C-n> to see the functionality

I have this is awkward in PHP script....
Please checkout and report

**Comment by ehzShelter** [comment]
<C-n> was due to sparkup html plugin ...<C-n> searching for empty tag !

Now I have removed it ....check recent push....and pull it....
Thanks for contribution....
